openapi: "3.0.0"
servers:
 - url: https://{environment}.osis.uclouvain.be/partnerships/v1
   variables:
     environment:
       default: dev
       enum:
         - dev # Development server
         - qa # Staging server
         - test # Test server
 - url: https://osis.uclouvain.be/partnerships/v1
   description: Production server
info:
  version: 1.0.0
  title: OSIS Partnerships
components:
  schemas:
    ValueLabel:
      type: object
      required:
        - id
        - label
      description: An label associated with an id
      example:
        id: 2
        label: value
      properties:
        id:
          type: string
        label:
          type: string
    Entity:
      description: An entity
      example:
        title: Science
        acronym: SC
      properties:
        title:
          type: string
        acronym:
          type: string
    Funding:
      description: A funding with a name and a url
      example:
        name: Erasmus
        url: https://erasmus.com/
      properties:
        name:
          type: string
        url:
          type: string
          format: uri
    Contact:
      type: object
      description: A contact with a name, a phone and an email
      example:
        first_name: John
        last_name: Doe
        phone: +33245678987
        email: john.doe@example.com
      properties:
        title:
          type: string
          description: mainly mr or mme
        first_name:
          type: string
        last_name:
          type: string
        phone:
          type: string
        email:
          type: string
          format: email
    PartnerListItem:
      type: object
      description: A partner for list display
      example:
        uuid: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
        name: Middle East Technical University
        city: Ankara
        country: Turquie
        country_iso: TK
        location: [10.0, 7.0]
        partnerships_count: 1
      properties:
        uuid:
          type: string
        name:
          type: string
        city:
          type: string
        country:
          type: string
        country_iso:
          type: string
        partnerships_count:
          type: number
        location:
          type: array
          items:
            type: number
          minItems: 2
          maxItems: 2
    Partner:
      type: object
      description: A complete description of a partner
      example:
        uuid: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
        name: Middle East Technical University
        website: https://example.com
        erasmus_code: TR ANKARA04
        partner_type: Université ou IES
        city: Ankara
        country: Turquie
        country_iso: TK
        partnerships_count: 1
        subject_area:
          - Subject 1
          - Subject 2
      properties:
        uuid:
          type: string
        name:
          type: string
        website:
          type: string
        erasmus_code:
          type: string
        partner_type:
          type: string
        city:
          type: string
        country:
          type: string
        country_iso:
          type: string
        partnerships_count:
          type: number
        subject_area:
          type: array
          items:
            type: string
    Partnership:
      type: object
      description: A complete description of a partnership
      example:
        uuid: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
        url: http://example.com/partnerships/v1/partnerships/a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
        partner:
          uuid: 9ffd7092-22b2-40b0-a95a-28beb6fe8ed8
          name: Middle East Technical University
          website: https://example.com
          erasmus_code: TR ANKARA04
          partner_type: Université ou IES
          city: Ankara
          country: Turquie
          country_iso: TK
        supervisor: John DOE
        type: Partneriat de mobilité
        partnership_type: MOBILITY
        ucl_sector: SSH
        ucl_faculty:
          title: Faculté des sciences
          acronym: FIAL
        ucl_entity:
          title: science
          acronym: SC
        is_sms: false
        is_smp: false
        is_smst: false
        is_sta: true
        is_stt: false
        missions: Enseignement
        subtype: Collaboration
        description: Lorem ipsum dolor amet et consectuer
        id_number: 16-6429845-FR
        project_title: Project X
        funding_program: Funding B
        education_fields:
          - Field 1
          - Field 2
        status:
          status: validated
          valid_years: 2019-2022
        partner_entity: Entity ABC
        medias:
          - url: http://example.com/file1
            name: file 1
        bilateral_agreements:
          - url: http://example.com/file1
            name: file 1
        out_education_levels:
          - Level 1
          - Level 2
        out_entities:
          - acronym: FIAL
            title: School of something
        out_university_offers:
          - Offer 1
        out_contact:
          first_name: John
          last_name: Doe
          phone: +33245678987
          email: john.doe@example.com
        out_portal: https://example.com
        out_funding:
          name: Erasmus
          url: https://erasmus.com/
        out_partner_contacts:
          - title: mr
            first_name: John
            last_name: Doe
            phone: +33245678987
            email: john.doe@example.com
        out_course_catalogue:
          fr:
            text: Course catalogue
            url: http://course.fr
          en:
            text: Course catalogue
            url: http://course.en
        out_summary_tables:
          - url: http://example.com/file1
            name: file 1
        in_contact:
          first_name: John
          last_name: Doe
          phone: +33245678987
          email: john.doe@example.com
        in_portal: https://example.com
        staff_contact_name: John DOE
        staff_partner_contacts:
          - title: mr
            first_name: John
            last_name: Doe
            phone: +33245678987
            email: john.doe@example.com
        staff_funding:
          name: Erasmus
          url: https://erasmus.com/
      properties:
        uuid:
          type: string
        url:
          type: string
        partner:
          $ref: '#/components/schemas/Partner'
        supervisor:
          type: string
        type:
          type: string
          description: Human-readable label of the type
        partnership_type:
          type: string
          description: Enum value of the type
        ucl_sector:
          type: string
          description: Acronym of the sector
        ucl_faculty:
          $ref: '#/components/schemas/Entity'
        ucl_entity:
          $ref: '#/components/schemas/Entity'
        is_sms:
          type: boolean
        is_smp:
          type: boolean
        is_smst:
          type: boolean
        is_sta:
          type: boolean
        is_stt:
          type: boolean
        missions:
          type: string
        subtype:
          type: string
        description:
          type: string
        id_number:
          type: string
        project_title:
          type: string
        funding_program:
          type: string
        education_fields:
          type: array
          items:
            type: string
        status:
          type: object
          properties:
            status:
              type: string
              enum:
                - waiting
                - validated
                - refused
            valid_years:
              type: string
        medias:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        bilateral_agreements:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        out_education_levels:
          type: array
          items:
            type: string
        out_entities:
          type: array
          items:
            $ref: '#/components/schemas/Entity'
        out_university_offers:
          type: array
          items:
            type: string
        out_contact:
          allOf:
            - $ref: '#/components/schemas/Contact'
          description: UCL contact
        out_portal:
          type: string
          format: uri
        out_funding:
          $ref: '#/components/schemas/Funding'
        out_partner_contacts:
          description: Contacts in partner institution
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        out_course_catalogue:
          description: Course catalogue in FR and EN
          type: object
          properties:
            fr:
              type: object
              properties:
                text:
                  type: string
                url:
                  type: string
                  format: uri
            en:
              type: object
              properties:
                text:
                  type: string
                url:
                  type: string
                  format: uri
        out_summary_tables:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              url:
                type: string
        in_contact:
          $ref: '#/components/schemas/Contact'
        in_portal:
          type: string
          format: uri
        staff_contact:
          description: UCL contact
          $ref: '#/components/schemas/Contact'
        staff_partner_contacts:
          description: Contacts in partner institution
          type: array
          items:
            $ref: '#/components/schemas/Contact'
        staff_funding:
          $ref: '#/components/schemas/Funding'
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
  parameters:
    limit:
      name: limit
      in: query
      description: How many items to return at one time
      schema:
        type: integer
        format: int32
        maximum: 100
        default: 25
        example: 42
    offset:
      name: offset
      in: query
      description: The initial index from which to return the results.
      schema:
        type: integer
        example: 51
    country:
      name: country
      in: query
      description: The country iso code
      schema:
        type: string
        example: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
    city:
      name: city
      in: query
      description: The city name
      schema:
        type: string
        example: Paris
    partner:
      name: partner
      in: query
      description: The uuid of the partner
      schema:
        type: string
        example: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
    ucl_entity:
      name: ucl_entity
      in: query
      description: The uuid of the faculty or school
      schema:
        type: string
        example: a84eda90-9f0a-4ea7-a70c-cab8cbdc3f21
    with_children:
      name: with_children
      in: query
      description: If children of ucl_entity should be taken into account
      schema:
        type: boolean
    education_level:
      name: education_level
      in: query
      description: The education level code
      schema:
        type: string
        example: ISCED-5
    type:
      name: type
      in: query
      description: The type of partnership
      schema:
        type: string
        example: MOBILITY
        enum:
          - GENERAL
          - MOBILITY
          - COURSE
          - DOCTORATE
          - PROJECT
    mobility_type:
      name: mobility_type
      in: query
      description: The type of mobility, either for student or for staff
      schema:
        type: string
        example: student
        enum:
          - student
          - staff
    funding_source:
      name: funding_source
      in: query
      description: The source id of funding
      schema:
        type: number
        example: 10
    funding_program:
      name: funding_program
      in: query
      description: The program id of funding
      schema:
        type: number
        example: 10
    funding_type:
      name: funding_type
      in: query
      description: The type id of funding
      schema:
        type: number
        example: 10
  responses:
    BadRequest:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
paths:
  /configuration:
    get:
      summary: List all possible values for parameters on other endpoints
      tags:
        - partners
      operationId: getPartnershipsConfiguration
      responses:
        '200':
          description: The list of possible values for parameters on other endpoints
          content:
            application/json:
              schema:
                properties:
                  continents:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        countries:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              iso_code:
                                type: string
                              cities:
                                type: array
                                items:
                                  type: string
                  partners:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  ucl_universities:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  education_levels:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  partnership_types:
                    type: array
                    items:
                      $ref: '#/components/schemas/ValueLabel'
                  fundings:
                    type: array
                    items:
                      type: object
                      properties:
                        value:
                          type: string
                        text:
                          type: string
                  partner_tags:
                    type: array
                    items:
                      type: string
                  tags:
                    type: array
                    items:
                      type: string
  /partners:
    get:
      summary: List all partners
      tags:
        - partners
      operationId: getPartnersList
      parameters:
        - in: query
          name: ordering
          description: The ordering of the items returned
          schema:
            type: string
            default: partner
            example: country_en
            enum:
              - partner
              - country_en
              - city
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/city'
        - $ref: '#/components/parameters/partner'
        - $ref: '#/components/parameters/ucl_entity'
        - $ref: '#/components/parameters/with_children'
        - $ref: '#/components/parameters/education_level'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/mobility_type'
        - $ref: '#/components/parameters/funding_type'
        - $ref: '#/components/parameters/funding_program'
        - $ref: '#/components/parameters/funding_source'
      responses:
        '200':
          description: An array of partners
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Partner'
        '400':
          $ref: '#/components/responses/BadRequest'
  /partnerships:
    get:
      summary: List all partnerships
      tags:
        - partnerships
      operationId: getPartnershipsList
      parameters:
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/offset'
        - $ref: '#/components/parameters/country'
        - $ref: '#/components/parameters/city'
        - $ref: '#/components/parameters/partner'
        - $ref: '#/components/parameters/ucl_entity'
        - $ref: '#/components/parameters/with_children'
        - $ref: '#/components/parameters/education_level'
        - $ref: '#/components/parameters/mobility_type'
        - $ref: '#/components/parameters/type'
        - $ref: '#/components/parameters/funding_type'
        - $ref: '#/components/parameters/funding_program'
        - $ref: '#/components/parameters/funding_source'
      responses:
        '200':
          description: A paged array of partnerships
          content:
            application/json:
              schema:
                type: object
                properties:
                  count:
                    type: integer
                  next:
                    type: string
                    format: uri
                  previous:
                    type: string
                    format: uri
                  results:
                    type: array
                    items:
                      $ref: '#/components/schemas/Partnership'
        '400':
          $ref: '#/components/responses/BadRequest'
  /partnerships/{uuid}:
    get:
      summary: Get the detail for a particular partnership
      tags:
        - partnerships
      operationId: getPartnershipsDetail
      parameters:
        - in: path
          name: uuid
          required: true
          schema:
            type: string
            format: uuid
            example: 'abcd-efgh-ijkl-mnop-1234-5678'
      responses:
        '200':
          description: A partnership
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Partnership'
        '404':
          $ref: '#/components/responses/NotFound'
